import compression from 'compression';
import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import { env } from './config/env.js';
import { asyncHandler } from './core/async-handler.js';
import { pool } from './database/pool.js';
import { requestContext } from './middleware/request-context.js';
import { errorHandler, notFoundHandler } from './middleware/error-handler.js';
import { authenticate } from './middleware/auth.js';
import { authRouter } from './modules/auth/auth.routes.js';
import { catalogsRouter } from './modules/catalogs/catalogs.routes.js';
import { groupsRouter } from './modules/groups/groups.routes.js';
import { corralsRouter, locationsRouter, pasturesRouter } from './modules/locations/locations.routes.js';
import { animalsRouter } from './modules/animals/animals.routes.js';
import { animalImagesRouter, imagesRouter } from './modules/images/images.routes.js';
import { selectionRouter } from './modules/selection/selection.routes.js';
import { movementsRouter } from './modules/movements/movements.routes.js';
import { sanitaryRouter } from './modules/sanitary/sanitary.routes.js';
import { cleaningsRouter } from './modules/cleanings/cleanings.routes.js';
import { operatorsRouter } from './modules/operators/operators.routes.js';
import { birthsRouter, recordsRouter } from './modules/records/records.routes.js';
import { rolesRouter, usersRouter } from './modules/admin/admin.routes.js';
import { dashboardRouter } from './modules/dashboard/dashboard.routes.js';
import { versionsRouter } from './modules/versions/versions.routes.js';
import { auditRouter } from './modules/audit/audit.routes.js';
import { salesRouter } from './modules/sales/sales.routes.js';
import { marksRouter } from './modules/marks/marks.routes.js';
import { reproductionRouter } from './modules/reproduction/reproduction.routes.js';
import { settingsRouter } from './modules/settings/settings.routes.js';
import { purchasesRouter } from './modules/purchases/purchases.routes.js';
import { activitiesRouter } from './modules/activities/activities.routes.js';
import { healthRouter } from './modules/health/health.routes.js';
import { bootstrapRouter } from './modules/bootstrap/bootstrap.routes.js';

export const app=express();
app.set('trust proxy',1);
app.use(requestContext);
app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'}}));
app.use(cors({origin:env.FRONTEND_URL.split(',').map(x=>x.trim()),credentials:true}));
app.use(compression());
app.use(express.json({limit:'2mb'}));
app.use(express.urlencoded({extended:true,limit:'2mb'}));
app.get('/health', asyncHandler(async (_req, res) => {
  await pool.query('SELECT 1');
  return res.json({ ok: true, service: 'SIGVB API', database: 'ok', time: new Date().toISOString() });
}));
const api=express.Router();
api.use('/auth',authRouter);
api.use('/versiones',versionsRouter);
// Debe permanecer antes de `authenticate`: crea únicamente el primer administrador
// y exige una clave temporal configurada en el entorno del servidor.
api.use('/bootstrap',bootstrapRouter);
api.use(authenticate);
api.use('/dashboard',dashboardRouter);
api.use('/catalogos',catalogsRouter);
api.use('/marquillas',marksRouter);
api.use('/grupos',groupsRouter);
api.use('/ubicaciones',locationsRouter);
api.use('/potreros',pasturesRouter);
api.use('/corrales',corralsRouter);
api.use('/animales/:id/imagenes',animalImagesRouter);
api.use('/animales',animalsRouter);
api.use('/imagenes',imagesRouter);
api.use('/selecciones',selectionRouter);
api.use('/movimientos',movementsRouter);
api.use('/jornadas-sanitarias',sanitaryRouter);
api.use('/limpiezas-potrero',cleaningsRouter);
api.use('/operadores',operatorsRouter);
api.use('/partos',birthsRouter);
api.use('/reproduccion',reproductionRouter);
api.use('/registros',recordsRouter);
api.use('/usuarios',usersRouter);
api.use('/roles',rolesRouter);
api.use('/auditoria',auditRouter);
api.use('/ventas',salesRouter);
api.use('/compras',purchasesRouter);
api.use('/actividades',activitiesRouter);
api.use('/condiciones-salud',healthRouter);
api.use('/configuracion',settingsRouter);
app.use(env.API_PREFIX,api);
app.use(notFoundHandler);
app.use(errorHandler);
